config/routes.rb
Rails.application.routes.draw do

  devise_for :customers


  root to: 'homes#top'
  get '/about' => 'homes#about'
  delete '/cart_items' => 'cart_items#destroy'
  resource :customers
  resources :items, only:[:index, :show]
  resources :cart_items


devise_for :admins, controllers: {
  sessions: 'admins/sessions'
}

  namespace :admin do
    resources :customers
    resources :items
    resources :genres
    resources :orders
    resources :order_details
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  def full_name
    self.last_name + self.first_name
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page]).order("id")

  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end


end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  def configure_sign_in_params
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && !@customer.is_active
        redirect_to new_customer_session_path
      end
    end
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!
  def show
    @customer = current_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    @customer.update(customer_params)
    redirect_to customers_path
  end

  def confirmation
  end

  def status
    @customer = current_customer
    @customer.update(is_active: false)
    reset_session
    redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/confirmation.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-10 col-lg-8 px-sm-0 text-center mb-4 mt-5">
      <strong>本当に退会しますか？</strong>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12 col-md-10 col-lg-8 px-sm-0 text-center">
      <p class="mb-5">
        退会すると、会員登録情報や</br>
        これまでの購入履歴が閲覧できなくなります。</br>
        退会する場合は、「退会する」をクリックしてください。
      </p>
      <%= link_to "退会しない", customers_path, class: "btn btn-primary px-4 mr-3" %>
      <%= link_to "退会する", customers_status_path(@customer), method: :patch, "data-confirm" => "本当に退会しますか？", class: "btn btn-danger px-4" %>
    </div>
  </div>
</div>

app/views/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-7 col-lg-6 px-5 px-sm-0">
      <h4 class="my-5"><span class="px-4 title">会員情報編集</span></h4>
    </div>
  </div>

  <%= form_with model: @customer, url: customers_path, local:true do |f| %>

  <div class="row mb-2">
    <div class="col-sm-2 col-md-2 col-lg-2 px-sm-0">
      <strong>氏名</strong>
    </div>
    <div class="col-sm-5 col-md-4 col-lg-4 px-sm-0">
      <%= f.text_field :last_name %>
    </div>
    <div class="col-sm-5 col-md-4 col-lg-4 px-sm-0">
      <%= f.text_field :first_name %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-sm-2 col-md-2 col-lg-2 px-sm-0">
      <strong>フリガナ</strong>
    </div>
    <div class="col-sm-5 col-md-4 col-lg-4 px-sm-0">
      <%= f.text_field :last_name_kana %>
    </div>
    <div class="col-sm-5 col-md-4 col-lg-4 px-sm-0">
      <%= f.text_field :first_name_kana %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-sm-2 col-md-2 col-lg-2 px-sm-0">
      <strong>郵便番号</strong>
    </div>
    <div class="col-sm-5 col-md-4 col-lg-4 px-sm-0">
      <%= f.text_field :postal_code %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-sm-2 col-md-2 col-lg-2 px-sm-0">
      <strong>住所</strong>
    </div>
    <div class="col-sm-10 col-md-10 col-lg-10 px-sm-0">
      <%= f.text_field :address, class: "customer-edit" %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-sm-2 col-md-2 col-lg-2 px-sm-0">
      <strong>電話番号</strong>
    </div>
    <div class="col-sm-5 col-md-4 col-lg-4 px-sm-0">
      <%= f.text_field :telephone_number %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-sm-2 col-md-2 col-lg-2 px-sm-0">
      <strong>メールアドレス</strong>
    </div>
    <div class="col-sm-5 col-md-4 col-lg-4 px-sm-0">
      <%= f.text_field :email %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-sm-2 col-md-2 col-lg-2 px-sm-0">
      <p></p>
    </div>
    <div class="col-sm-5 col-md-4 col-lg-4 px-sm-0">
      <%= f.submit "編集内容を保存", class: "btn btn-sm btn-success mt-4 new" %>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2 px-sm-0">
      <p></p>
    </div>
    <div class="col-sm-3 col-md-3 col-lg-3 px-sm-0">
      <%= link_to "退会する", '/customers/confirmation', class: "btn btn-sm btn-danger mt-4 px-3"%>
    </div>
  </div>
  <% end %>

app/views/customers/show.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-10 col-lg-8 px-sm-0">
        <h5 class="ml-5 my-4"><span class="px-3 title">マイページ</span></h5>
      </div>
    </div>

    <div class="row align-items-center my-3">
      <div class="col-sm-2 col-md-2 col-lg-2 px-sm-0">
        <h5>登録情報</h5>
      </div>

      <div class="col-sm-3 col-md-3 col-lg-3 px-sm-0">
        <%= link_to "編集する", edit_customers_path, class: "btn btn-success px-4 py-1" %>
      </div>
    </div>

    <table>
      <tbody>
        <tr>
          <td class="grid pl-2 pr-5 py-2">氏名</td>
          <td class="grid-item pl-2 pr-5 py-2"><%= @customer.last_name %> <%= @customer.first_name %></td>
        </tr>

        <tr>
          <td class="grid pl-2 pr-5 py-2">カナ</td>
          <td class="grid-item pl-2 pr-5 py-2"><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
        </tr>

        <tr>
          <td class="grid pl-2 pr-5 py-2">郵便番号</td>
          <td class="grid-item pl-2 pr-5 py-2"><%= @customer.postal_code %></td>
        </tr>

        <tr>
          <td class="grid pl-2 pr-5 py-2">住所</td>
          <td class="grid-item pl-2 pr-5 py-2"><%= @customer.address %></td>
        </tr>

        <tr>
          <td class="grid pl-2 pr-5 py-2">電話番号</td>
          <td class="grid-item pl-2 pr-5 py-2"><%= @customer.telephone_number %></td>
        </tr>

        <tr>
          <td class="grid pl-2 pr-5 py-2">メールアドレス</td>
          <td class="grid-item pl-2 pr-5 py-2"><%= @customer.email %></td>
        </tr>

        </tr>
      </tbody>
    </table>

    <div class="row align-items-center my-3">
      <div class="col-sm-2 col-md-2 col-lg-2 px-sm-0">
        <h5>配送先</h5>
      </div>
      <div class="col-sm-3 col-md-3 col-lg-3 px-sm-0">
        <%= link_to "一覧を見る", addresses_path, class: "btn btn-primary px-4 py-1" %>
      </div>
    </div>

    <div class="row align-items-center my-3">
      <div class="col-sm-2 col-md-2 col-lg-2 px-sm-0">
        <h5>注文履歴</h5>
      </div>
      <div class="col-sm-3 col-md-3 col-lg-3 px-sm-0">
        <%= link_to "一覧を見る", orders_path, class: "btn btn-primary px-4 py-1" %>
      </div>
    </div>
  </div>
</main>