config/routes.rb
Rails.application.routes.draw do

  devise_for :customers


  root to: 'homes#top'
  get '/about' => 'homes#about'
  delete '/cart_items' => 'cart_items#destroy'
  resource :customers
  resources :items, only:[:index, :show]
  resources :cart_items


devise_for :admins, controllers: {
  sessions: 'admins/sessions'
}

  namespace :admin do
    resources :customers
    resources :items
    resources :genres
    resources :orders
    resources :order_details
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  def order_price
    billing - 800
  end
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum received: {
    waiting: 0,
    confirmation: 1,
    producing: 2,
    preparing: 3,
    sent: 4
  }

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])

  end

  def update
    @order = Order.find(params[:id])
    @order.update(received:params[:order][:received])
    if @order.received == "confirmation"
      @order.order_details.update_all(making_status: 1)
    end
    redirect_to admin_order_path(@order.id)
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :shipping_zip_code, :shipping_address, :delivery_name, :payment_method, :billing)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_customer!
  def new
    @customer = current_customer
    @address = current_customer.address
    @order = Order.new
  end

  def confirmation
    @cart_items = current_customer.cart_items
    @total = @cart_items.inject(0) { |sum, item| sum + item.subtotal }
    @total_price = (@total + 800)
    @order = Order.new(order_params)
    if params[:order][:address_name] == "0"
      @order.shipping_zip_code = current_customer.postal_code
      @order.shipping_address = current_customer.address
      @order.delivery_name = current_customer.last_name + current_customer.first_name
    elsif params[:order][:address_name] == "1"
      @address = Address.find(params[:order][:address_id])
      @order.shipping_zip_code = @address.postal_code
      @order.shipping_address = @address.address
      @order.delivery_name = @address.name
    elsif params[:order][:address_name] == "2"

    else
      redirect_to new_orders_path
    end
  end

  def thanks
  end

  def create
    cart_items = current_customer.cart_items.all
    @order = current_customer.orders.new(order_params)
    if @order.save
      cart_items.each do |cart_item|
        order_detail = OrderDetail.new
        order_detail.item_id = cart_item.item_id
        order_detail.order_id = @order.id
        order_detail.amount = cart_item.amount
        order_detail.price_time = cart_item.item.price
        order_detail.save
      end
      redirect_to orders_thanks_path
      cart_items.destroy_all
    else
      @order = Order.new(order_params)
      render :new
    end
  end

  def index
    @orders = current_customer.orders

  end

  def show
    @order = Order.find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :shipping_zip_code, :shipping_address, :delivery_name, :payment_method, :billing)
  end
end

app/helpers/admin/order_helper.rb
module Admin::OrderHelper
end

app/views/orders/confirmation.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-md-8 col-lg-8 px-sm-0">
      <h5 class="mt-4 mb-3 ml-4"><span class="px-4 title">注文情報確認</span></h5>
    </div>
  </div>
  <div class="table-style">
    <div>
    <table>
      <thead>
        <tr>
          <th class="pl-2 pr-5 py-2 grid">商品名</th>
          <th class="pl-2 pr-sm-3 pr-md-3 pr-lg-5 py-2 grid">単価(税込)</th>
          <th class="pl-2 pr-sm-3 pr-md-3 pr-lg-5 py-2 grid">数量</th>
          <th class="pl-2 pr-sm-3 pr-md-3 pr-lg-5 py-2 grid">小計</th>
        </tr>
      </thead>
      <tbody>
      <% @cart_items.each do |cart_item| %>
        <tr>
          <td class="pl-2 pr-5 grid-item">
            <%= attachment_image_tag cart_item.item, :image, class: "p-2 cart-item-image" %>
            <%= cart_item.item.name %>
          </td>
          <td class="pl-2 pr-sm-3 pr-md-3 pr-lg-5 grid-item"><%= cart_item.item.with_tax_price.to_s(:delimited) %></td>
          <td class="pl-2 pr-sm-3 pr-md-3 pr-lg-5 grid-item"><%= cart_item.amount %></td>
          <td class="pl-2 pr-sm-3 pr-md-3 pr-lg-5 grid-item"><%= cart_item.subtotal.to_s(:delimited) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    </div>
    <div>
      <table>
        <thead>
          <tr>
            <td class="pl-5 py-2"></th>
            <td class="pl-2 pr-sm-3 pr-md-3 pr-lg-5 py-2 grid">送料</th>
            <td class="pl-2 pr-sm-3 pr-md-3 pr-lg-5 py-2 grid-item">800</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="pl-5"></td>
            <td class="pl-2 pr-sm-3 pr-md-3 pr-lg-5 py-2 grid">商品合計</td>
            <td class="pl-2 pr-sm-3 pr-md-3 pr-lg-5 py-2 grid-item"><%= @total.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="pl-5"></td>
            <td class="pl-2 pr-sm-3 pr-md-3 pr-lg-5 py-2 grid">請求金額</td>
            <td class="pl-2 pr-sm-3 pr-md-3 pr-lg-5 py-2 grid-item"><%= @total_price.to_s(:delimited) %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row my-4">
    <div class="col-sm-2 col-md-2 col-lg-1 px-sm-0">
      <h5 class="mr-2">支払方法</h5>
    </div>
    <div class="col-sm-8 col-md-8 col-lg-8 px-sm-0">
      <%= @order.payment_method_i18n %>
    </div>
  </div>

  <div class="row mb-4">
    <div class="col-sm-2 col-md-2 col-lg-1 px-sm-0">
      <h5 class="mr-2">お届け先</h5>
    </div>
    <div class="col-sm-8 col-md-8 col-lg-8 px-sm-0">
      <p>
        〒<%= @order.shipping_zip_code %><%= @order.shipping_address %></br>
        <%= @order.delivery_name %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 text-center">
      <%= form_with model: @order, url: orders_path, method: :post, local:true do |f| %>
        <%= f.hidden_field :payment_method %>
        <%= f.hidden_field :shipping_zip_code %>
        <%= f.hidden_field :delivery_name %>
        <%= f.hidden_field :shipping_address %>
        <%= f.hidden_field :billing, value: @total_price %>
        <%= f.submit "注文を確定する", class: "btn btn-success px-4" %>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-md-8 col-lg-8 px-sm-0">
      <h5 class="mt-4 mb-3 ml-4"><span class="px-4 title">注文履歴一覧</span></h5>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th class="pl-2 grid">注文日</th>
        <th class="pl-2 grid">配送先</th>
        <th class="pl-2 grid">注文商品</th>
        <th class="pl-2 pr-sm-2 grid">支払金額</th>
        <th class="pl-2 pr-sm-2 grid">ステータス</th>
        <th class="pl-2 pr-sm-2 grid">注文詳細</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.reverse.each do |order| %>
      <tr>
        <td class="pl-2 pr-5 grid-item"><%= order.created_at.strftime("%Y/%m/%d") %></td>
        <td class="pl-2 pr-5 grid-item">
          〒<%= order.shipping_zip_code %></br>
          <%= order.shipping_address %></br>
          <%= order.delivery_name %>
        </td>
        <td class="pl-2 pr-sm-2 grid-item">
          <% order.order_details.each do |order_detail| %>
            <%= order_detail.item.name %>
          <% end %>
        </td>
        <td class="pl-2 pr-3 grid-item"><%= order.billing.to_i.to_s(:delimited) %>円</td>
        <td class="pl-2 pr-4 grid-item"><%= order.received_i18n %></td>
        <td class="p-sm-2 grid-item"><%= link_to "表示する", order_path(order.id), class: "btn btn-primary" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/orders/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-md-8 col-lg-8 px-sm-0">
      <h5 class="mt-4 mb-3 ml-4"><span class="px-4 title">注文情報入力</span></h5>
    </div>
  </div>
  <%= form_with model: @order, url: orders_confirmation_path, method: :post, local:true do |f| %>
  <div class="row mb-2">
    <div class="col-sm-12 col-md-12 col-lg-10 px-sm-0">
      <h5>支払方法</h5>
      <%= f.radio_button :payment_method, "credit_card", class: "ml-4" %>
      <%= f.label :payment_method, "クレジットカード", class: "mb-0" %></br>
      <%= f.radio_button :payment_method, "transfer", class: "ml-4" %>
      <%= f.label :payment_method, "銀行振込", class: "mb-0" %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-sm-10 col-md-10 col-lg-10 px-sm-0">
      <h5>お届け先</h5>
      <%= f.radio_button :address_name, 0, class: "ml-4" %>
      <%= f.label :customer_id, "ご自身の住所", class: "mb-0" %>
      <p class="ml-5">〒<%= @customer.postal_code %> <%= @customer.address %></p>
      <p class="ml-5"><%= @customer.full_name %></p>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-sm-10 col-md-10 col-lg-10 px-sm-0">
      <%= f.radio_button :address_name, 1, class: "ml-4" %>
      <%= f.label :address_id, "登録済みの住所から選択", class: "mb-0" %></br>
      <p class="ml-5"><%= f.select :address_id, options_from_collection_for_select(current_customer.addresses, :id, :full_address) %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-10 col-md-10 col-lg-10 px-sm-0">
      <%= f.radio_button :address_name, 2, class: "ml-4" %>
      <%= f.label :address, "新しいお届け先", class: "mb-0" %></br>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-sm-5 col-md-3 col-lg-3 px-sm-0">
      <p class="pl-5">郵便番号(ハイフンなし)</p>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-6 px-sm-0">
      <%= f.text_field :shipping_zip_code %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-sm-5 col-md-3 col-lg-3 px-sm-0">
      <p class="pl-5">住所</p>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-5 px-sm-0">
      <%= f.text_field :shipping_address, class: "new" %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-sm-5 col-md-3 col-lg-3 px-sm-0">
      <p class="pl-5">宛名</p>
    </div>
    <div class="col-sm-5 col-md-4 col-lg-4 px-sm-0">
      <%= f.text_field :delivery_name %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12 col-md-11 col-lg-10 px-sm-0">
      <p class="text-center"><%= f.submit "確認画面へ進む", class: "btn btn-primary" %></p>
    </div>
　</div>
　<% end %>
</div>

app/views/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-md-8 col-lg-8 px-sm-0">
      <h5 class="mt-4 mb-5 ml-4"><span class="px-4 title">注文履歴詳細</span></h5>
    </div>
  </div>
  <div class="table-style">
    <div class="mr-2">
      <table>
        <thead>
          <tr>
            <th class="py-2">注文情報</th>
          </tr>
          <tr>
            <td class="pl-1 grid">注文日</td>
            <td class="p-sm-2 grid-item"><%= @order.created_at.strftime("%Y/%m/%d") %></td>
          </tr>
          <tr>
            <td class="pl-1 pr-5 py-2 grid">配送先</td>
            <td class="p-sm-2 grid-item">
              〒<%= @order.shipping_zip_code %></br>
              <%= @order.shipping_address %></br>
              <%= @order.delivery_name %>
            </td>
          </tr>
          <tr>
            <td class="pl-1 pr-5 py-2 grid">支払方法</td>
            <td class="p-sm-2 grid-item"><%= @order.payment_method_i18n %></td>
          </tr>
          <tr>
            <td class="pl-1 pr-5 py-2 grid">ステータス</td>
            <td class="p-sm-2 grid-item"><%= @order.received_i18n %></td>
          </tr>
        </thead>
      </table>
    </div>

    <div>
      <table>
        <thead>
          <tr>
            <th class="py-2">請求情報</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="pl-1 pr-5 py-2 grid">商品合計</td>
            <td class="pl-1 pr-5 py-2 grid-item"><%= @order.order_price.to_s(:delimited) %></td>
          </tr>
          <tr>
            <td class="pl-1 pr-5 py-2 grid">配送料</td>
            <td class="pl-1 pr-5 py-2 grid-item">800</td>
          </tr>
          <tr>
            <td class="pl-1 pr-5 py-2 grid">ご請求額</td>
            <td class="pl-1 pr-5 py-2 grid-item"><%= @order.billing.to_i.to_s(:delimited) %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th class="py-2">注文内容</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="pl-1 pr-5 py-2 grid">商品</td>
        <td class="pl-1 pr-5 py-2 grid">単価（税込）</td>
        <td class="pl-1 pr-5 py-2 grid">個数</td>
        <td class="pl-1 pr-5 py-2 grid">小計</td>
      </tr>
      <% @order.order_details.each do |order_detail| %>
      <tr>
        <td class="pl-1 pr-5 py-2 grid-item"><%= order_detail.item.name %></td>
        <td class="pl-1 pr-5 py-2 grid-item"><%= order_detail.price_detail %></td>
        <td class="pl-1 pr-5 py-2 grid-item"><%= order_detail.amount %></td>
        <td class="pl-1 pr-5 py-2 grid-item"><%= order_detail.detail_price %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/orders/thanks.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 px-sm-0 text-center thanks">
      <h4>ご注文ありがとうございました！</h4>
    </div>
  </div>
</div>