config/routes.rb
Rails.application.routes.draw do

  devise_for :customers


  root to: 'homes#top'
  get '/about' => 'homes#about'
  delete '/cart_items' => 'cart_items#destroy'
  resource :customers
  resources :items, only:[:index, :show]
  resources :cart_items


devise_for :admins, controllers: {
  sessions: 'admins/sessions'
}

  namespace :admin do
    resources :customers
    resources :items
    resources :genres
    resources :orders
    resources :order_details
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/addresse.rb
class Addresse < ApplicationRecord
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  def full_name
    self.last_name + self.first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details



  attachment :image
  def with_tax_price
    (price * 1.1).floor
  end


end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  def order_price
    billing - 800
  end
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum received: {
    waiting: 0,
    confirmation: 1,
    producing: 2,
    preparing: 3,
    sent: 4
  }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status: {
    restricting: 0,
    waiting: 1,
    producing: 2,
    preparing: 3
  }

  def detail_price
    price_detail * amount
  end

  def price_detail
    (price_time * 1.1).floor
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate_customer!
  def index
    @addresses = current_customer.addresses
    @address = Address.new
  end

  def edit
    @address = Address.find(params[:id])
  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    @address.save
    redirect_to addresses_path
  end

  def update
    @address = Address.find(params[:id])
    @address.update(address_params)
    redirect_to addresses_path
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to addresses_path
  end

  private

  def address_params
    params.require(:address).permit(:name, :address, :postal_code)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_customer!
  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    @cart_item.save
    redirect_to cart_items_path
  end

  def index
    @cart_items = current_customer.cart_items
    @total = @cart_items.inject(0) { |sum, item| sum + item.subtotal }

  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path
  end

  def empty
    current_customer.cart_items.destroy_all
    redirect_to cart_items_path
  end



  private

  def cart_item_params
    params.require(:cart_item).permit(:item_id, :amount)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!
  def show
    @customer = current_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    @customer.update(customer_params)
    redirect_to customers_path
  end

  def confirmation
  end

  def status
    @customer = current_customer
    @customer.update(is_active: false)
    reset_session
    redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all
  end

  def about
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_customer!,except: [:index, :show]
  def index
    @items = Item.page(params[:page]).per(8)
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end


end

app/controllers/order_details_controller.rb
class OrderDetailsController < ApplicationController
    before_action :authenticate_customer!
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_customer!
  def new
    @customer = current_customer
    @address = current_customer.address
    @order = Order.new
  end

  def confirmation
    @cart_items = current_customer.cart_items
    @total = @cart_items.inject(0) { |sum, item| sum + item.subtotal }
    @total_price = (@total + 800)
    @order = Order.new(order_params)
    if params[:order][:address_name] == "0"
      @order.shipping_zip_code = current_customer.postal_code
      @order.shipping_address = current_customer.address
      @order.delivery_name = current_customer.last_name + current_customer.first_name
    elsif params[:order][:address_name] == "1"
      @address = Address.find(params[:order][:address_id])
      @order.shipping_zip_code = @address.postal_code
      @order.shipping_address = @address.address
      @order.delivery_name = @address.name
    elsif params[:order][:address_name] == "2"

    else
      redirect_to new_orders_path
    end
  end

  def thanks
  end

  def create
    cart_items = current_customer.cart_items.all
    @order = current_customer.orders.new(order_params)
    if @order.save
      cart_items.each do |cart_item|
        order_detail = OrderDetail.new
        order_detail.item_id = cart_item.item_id
        order_detail.order_id = @order.id
        order_detail.amount = cart_item.amount
        order_detail.price_time = cart_item.item.price
        order_detail.save
      end
      redirect_to orders_thanks_path
      cart_items.destroy_all
    else
      @order = Order.new(order_params)
      render :new
    end
  end

  def index
    @orders = current_customer.orders

  end

  def show
    @order = Order.find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :shipping_zip_code, :shipping_address, :delivery_name, :payment_method, :billing)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/cart_items_helper.rb
module Admin::CartItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/views/cart_items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-md-8 col-lg-8 px-sm-0">
      <h5 class="mt-4 mb-3 ml-4"><span class="px-4 title">ショッピングカート</span></h5>
    </div>
    <div class="col-sm-4 col-md-4 col-lg-4 px-sm-0 py-3 text-right">
      <%= link_to "カートを空にする", cart_items_path, method: :delete, class: "btn btn-danger" %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-4 col-md-4 col-lg-3 px-sm-0 grid py-2">
      <strong class="pl-2">商品名</strong>
    </div>

    <div class="col-sm-2 col-md-2 col-lg-1 px-sm-0 head-grid py-2">
      <strong class="pl-2">単価(税込)</strong>
    </div>

    <div class="col-sm-3 col-md-2 col-lg-2 px-sm-0 head-grid py-2">
      <strong class="pl-2">数量</strong>
    </div>

    <div class="col-sm-1 col-md-2 col-lg-1 px-sm-0 head-grid py-2">
      <strong class="pl-2">小計</strong>
    </div>

    <div class="col-sm-2 col-md-2 col-lg-1 px-sm-0 head-grid">
      <p></p>
    </div>
  </div>

  <% @cart_items.each do |cart_item| %>

  <div class="row">
    <div class="col-sm-4 col-md-4 col-lg-3 px-sm-0 item-head-grid">
      <%= attachment_image_tag cart_item.item, :image, class: "p-2 cart-item-image" %>
      <%= cart_item.item.name %>
    </div>

    <div class="col-sm-2 col-md-2 col-lg-1 pl-2 item-grid py-2">
      <%= cart_item.item.with_tax_price.to_s(:delimited) %>
    </div>


    <div class="col-sm-3 col-md-2 col-lg-2 px-sm-0 item-grid py-1 px-1 pl-2 text-center">
    <%= form_with model: cart_item, local:true do |f| %>
      <%= f.select :amount, *[1..10], class: 'select-box my-1', require: true %>
      <%= f.submit "変更", class: "btn btn-sm btn-success" %>
    <% end %>
    </div>


    <div class="col-sm-1 col-md-2 col-lg-1 item-grid py-2 pl-2">
      <%= cart_item.subtotal.to_s(:delimited) %>
    </div>

    <div class="col-sm-2 col-md-2 col-lg-1 px-sm-0 item-grid py-1 text-center">
      <%= link_to "削除する", cart_item_path(cart_item.id), method: :delete, class: "btn btn-sm btn-danger" %>
    </div>
  </div>

  <% end %>

  <div class="row">
    <div class="col-sm-4 col-md-4 col-lg-3 px-sm-0 mt-4">
      <%= link_to "買い物を続ける", root_path, class: "btn btn-primary" %>
    </div>

    <div class="col-sm-4 col-md-4 col-lg-3 px-sm-0 mt-3">
      <p></p>
    </div>

    <div class="col-sm-2 col-md-2 col-lg-1 mt-3 px-sm-0 py-3 grid">
      <strong class="pl-2">合計金額</strong>
    </div>

    <div class="col-sm-2 col-md-2 col-lg-1 mt-3 py-3 pl-2 cart-item-grid">
      <%= @total.to_s(:delimited) %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-8 px-sm-0 mt-5 text-center">
    <% if @cart_items.empty? %>
    <% else %>
      <%= link_to "情報入力に進む", new_order_path, class: "btn btn-success px-3" %>
    <% end %>
    </div>
  </div>

</div>