config/routes.rb
Rails.application.routes.draw do

  devise_for :customers


  root to: 'homes#top'
  get '/about' => 'homes#about'
  delete '/cart_items' => 'cart_items#destroy'
  resource :customers
  resources :items, only:[:index, :show]
  resources :cart_items


devise_for :admins, controllers: {
  sessions: 'admins/sessions'
}

  namespace :admin do
    resources :customers
    resources :items
    resources :genres
    resources :orders
    resources :order_details
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/addresse.rb
class Addresse < ApplicationRecord
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  def full_name
    self.last_name + self.first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details



  attachment :image
  def with_tax_price
    (price * 1.1).floor
  end


end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  def order_price
    billing - 800
  end
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum received: {
    waiting: 0,
    confirmation: 1,
    producing: 2,
    preparing: 3,
    sent: 4
  }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status: {
    restricting: 0,
    waiting: 1,
    producing: 2,
    preparing: 3
  }

  def detail_price
    price_detail * amount
  end

  def price_detail
    (price_time * 1.1).floor
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate_customer!
  def index
    @addresses = current_customer.addresses
    @address = Address.new
  end

  def edit
    @address = Address.find(params[:id])
  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    @address.save
    redirect_to addresses_path
  end

  def update
    @address = Address.find(params[:id])
    @address.update(address_params)
    redirect_to addresses_path
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to addresses_path
  end

  private

  def address_params
    params.require(:address).permit(:name, :address, :postal_code)
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_customer!
  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    @cart_item.save
    redirect_to cart_items_path
  end

  def index
    @cart_items = current_customer.cart_items
    @total = @cart_items.inject(0) { |sum, item| sum + item.subtotal }

  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path
  end

  def empty
    current_customer.cart_items.destroy_all
    redirect_to cart_items_path
  end



  private

  def cart_item_params
    params.require(:cart_item).permit(:item_id, :amount)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!
  def show
    @customer = current_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    @customer.update(customer_params)
    redirect_to customers_path
  end

  def confirmation
  end

  def status
    @customer = current_customer
    @customer.update(is_active: false)
    reset_session
    redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.all
  end

  def about
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_customer!,except: [:index, :show]
  def index
    @items = Item.page(params[:page]).per(8)
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_customer!
  def new
    @customer = current_customer
    @address = current_customer.address
    @order = Order.new
  end

  def confirmation
    @cart_items = current_customer.cart_items
    @total = @cart_items.inject(0) { |sum, item| sum + item.subtotal }
    @total_price = (@total + 800)
    @order = Order.new(order_params)
    if params[:order][:address_name] == "0"
      @order.shipping_zip_code = current_customer.postal_code
      @order.shipping_address = current_customer.address
      @order.delivery_name = current_customer.last_name + current_customer.first_name
    elsif params[:order][:address_name] == "1"
      @address = Address.find(params[:order][:address_id])
      @order.shipping_zip_code = @address.postal_code
      @order.shipping_address = @address.address
      @order.delivery_name = @address.name
    elsif params[:order][:address_name] == "2"

    else
      redirect_to new_orders_path
    end
  end

  def thanks
  end

  def create
    cart_items = current_customer.cart_items.all
    @order = current_customer.orders.new(order_params)
    if @order.save
      cart_items.each do |cart_item|
        order_detail = OrderDetail.new
        order_detail.item_id = cart_item.item_id
        order_detail.order_id = @order.id
        order_detail.amount = cart_item.amount
        order_detail.price_time = cart_item.item.price
        order_detail.save
      end
      redirect_to orders_thanks_path
      cart_items.destroy_all
    else
      @order = Order.new(order_params)
      render :new
    end
  end

  def index
    @orders = current_customer.orders

  end

  def show
    @order = Order.find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :shipping_zip_code, :shipping_address, :delivery_name, :payment_method, :billing)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light border-bottom">
        <div class="container">
          <a class="navbar-brand p-3" href="/">nagano_cake</a>
          <% if customer_signed_in? %>
            <p>ようこそ、<%= current_customer.last_name %>さん！</p>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
            <li class="nav-item">
              <%= link_to "マイページ", customers_path, class: 'btn btn-outline-secondary nav-link text-dark ml-5' %>
            </li>
            <li class="nav-item">
              <%= link_to '商品一覧', items_path, class: 'btn btn-outline-secondary nav-link text-dark ml-5' %>
            </li>
            <li class="nav-item">
              <%= link_to 'カート', cart_items_path, class: 'btn btn-outline-secondary nav-link text-dark ml-5' %>
            </li>
            <li class="nav-item">
              <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: 'btn btn-outline-secondary nav-link text-dark ml-5' %>
            </li>
            <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to '商品一覧', admin_items_path, class: 'btn btn-outline-secondary nav-link text-dark ml-5' %>
            </li>
            <li class="nav-item">
              <%= link_to '会員一覧', admin_customers_path, class: 'btn btn-outline-secondary nav-link text-dark ml-5' %>
            </li>
            <li class="nav-item">
              <%= link_to '注文履歴一覧', "/admin", class: 'btn btn-outline-secondary nav-link text-dark ml-5' %>
            </li>
            <li class="nav-item">
              <%= link_to 'ジャンル一覧', admin_genres_path, class: 'btn btn-outline-secondary nav-link text-dark ml-5' %>
            </li>
            <li class="nav-item">
              <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'btn btn-outline-secondary nav-link text-dark ml-5' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "About", '/about', class: 'btn btn-outline-secondary nav-link text-dark ml-5' %>
            </li>
            <li class="nav-item">
              <%= link_to "商品一覧", items_path, class: 'btn btn-outline-secondary nav-link text-dark ml-5' %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-outline-secondary nav-link text-dark ml-5' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_customer_session_path, class: 'btn btn-outline-secondary nav-link text-dark ml-5' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>Nagano_cake.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>


</html>